### ISSUE TITLE
Deploy version 0.2.0

### ISSUE THREAD

**Issue by dvberkel** [moumar/clj-launchpad#2]
I would love to use the `open` function that excepts a Midi device name as added in commit ce7e1e3a6874a23629292eecaf4c29d8e15ef10b. Could a new version be deployed to [Clojars](https://clojars.org/clj-launchpad)?

**Comment by dvberkel** [comment]
If this is to much of a hassle for you I am happy to volunteer as a maintainer for the project. I would have to be added as a [collaborator](https://help.github.com/articles/adding-collaborators-to-a-personal-repository/) to the `clj-launchpad` repository and added to the Clojars [group](https://github.com/ato/clojars-web/wiki/Groups)

**Comment by moumar** [comment]
just added you as developer in clojars and github. enjoy ;)

**Comment by dvberkel** [comment]
Thanks!
