### ISSUE TITLE
Are the mercurial specific files still necessary?

### ISSUE THREAD

**Issue by dvberkel** [moumar/clj-launchpad#3]
There are two files specific to [mercurial](https://mercurial.selenic.com/), i.e. `.hgignore` & `.hgtags`.

Are they still used, or can they removed?

**Comment by moumar** [comment]
no problem Daan, you can do whatever you like with the library ;)

**Comment by dvberkel** [comment]
Thanks, I just want to be a nice contributor. Better safe than sorry
